version: '3'

volumes:
  postgres_volume:

services:
  pg:
    image: postgres:14-alpine3.17
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-54323}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "50055:50055"
    depends_on:
      - pg
    networks:
      - auth_default
      - chat-server_default

networks:
  auth_default:
    external: true
  chat-server_default:
    external: true